### PR TITLE
mobile viewport + jquery https

### PR DESCRIPTION
**Pull request by vdegenne**
I added the viewport metadata so the page renders well on mobile devices.
Also jquery import should be secure or else Chrome won't accept synchronous fetch.

### CODE REVIEW

**Comment by vdegenne** [comment]
Also I reduced the font-size for `#question` so on mobile up to 4 characters it won't break.

**Review by colspan — APPROVED** [review]
Thank you for your great work. LGTM

**Comment by vdegenne** [comment]
@colspan  Sorry to bother you again but I noticed you have a branch for github-page, I think you should remove it and use the `root` for the github page in the settings instead. Because this pull request is on the master branch the current github page was not affected by it.

By the way I found your app because it was first result in google search for `hanja quiz` search. Congrats!

**Comment by colspan** [comment]
@vdegenne Thank you for kind suggestion. Now I applied `master` branch as github-page.

**Pull request merged**
